"""Pydantic schemas for chat session and message records."""
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class MessageSessionBase(BaseModel):
    session_id: Optional[str] = Field(None, description="Client-visible conversation identifier")
    first_user_message: str = Field(..., description="Initial user prompt for the session")


class MessageSessionCreate(MessageSessionBase):
    user_id: int


class MessageSession(MessageSessionBase):
    id: int
    user_id: int
    created_at: datetime

    class Config:
        from_attributes = True


class UserMessageBase(BaseModel):
    session_id: str
    role: str = Field(default="user", description="Message author role (user or assistant)")
    user_message: Optional[str] = Field(None, description="Content provided by the user")
    ai_message: Optional[str] = Field(None, description="Content generated by the assistant")
    liked: Optional[bool] = None
    disliked: Optional[bool] = None


class UserMessageCreate(UserMessageBase):
    user_id: int


class UserMessage(UserMessageBase):
    id: int
    user_id: int
    created_at: datetime

    class Config:
        from_attributes = True
